# -*- coding: utf-8 -*-
"""Assignment_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e-KsdYSjRsZbsE0TpT7Y_QwMPmHeyU0Z
"""


R1 = {"name":"R_outside","type":"conv","material":"Outside Air"}
R2 = {"name":"R_woodB","type":"cond","material":"Wood Bevel","length":0.013}
R3 = {"name":"R_fiberboard","type":"cond","material":"fiberboard","length":0.013}
R4 = {"name":"R_glass","type":"cond","material":"Glass Fiber","length":0.09}
R5 = {"name":"R_Woodstud","type":"cond","material":"Wood Studs","length":0.09}
R6 = {"name":"R_gypsum","type":"cond","material":"Gypsum","length":0.013}
R7 = {"name":"R_inside","type":"conv","material":"Inside Air"}

StandardValues = {"Outside Air":{"RValUnit":0.03},
    "Wood Bevel":{"Standard_L":0.013, "RValUnit": 0.14}, 
    "fiberboard":{"Standard_L":0.013,"RValUnit":0.23},
    "Glass Fiber":{"Standard_L":0.025,"RValUnit":0.7},
    "Wood Studs":{"Standard_L":0.09, "RValUnit":0.63},
    "Gypsum":{"Standard_L":0.013,"RValUnit":0.079},
    "Inside Air":{"RValUnit":0.12}}

Rprime_wood =[R1,R2,R3,R5,R6,R7]
Rprime_glass=[R1,R2,R3,R4,R6,R7]

########Computing the individual and total resistances for each case (wood & glass fiber)

def Resistance(Res_list, name='material name'):
  Rtot = 0
  RL =[]
  for anyR in Res_list:
        if anyR["type"] == "conv":
          MatOfAnyR = anyR["material"]
          RValOfAnyR = StandardValues[MatOfAnyR]
          R_val_anyR =  RValOfAnyR["RValUnit"]
          RL.append(R_val_anyR)
          Rtot = Rtot + R_val_anyR
      
        elif anyR["type"] == "cond":
              lengthOfanyR = anyR["length"]
              MatOfAnyR= anyR["material"]
              dict1 = StandardValues[MatOfAnyR]
              standardLof_material = dict1["Standard_L"]
              standardR_ofMaterial = dict1["RValUnit"]
              R_val_anyR = (standardR_ofMaterial * lengthOfanyR)/standardLof_material
              RL.append(R_val_anyR)
              Rtot = Rtot + R_val_anyR
        U_value = round((1/Rtot),4)
  print('Unit Resistance List for '+ name +' :'  + str(RL) )       
  print('Total Unit Resistance for ' + name + ': ' + str(Rtot)+ ' °C/W.m^2' )
  print('Heat tranfer coef for ' + name + ': '+ str(U_value)+ ' W/m^2.°C' )
  return U_value

U_wood = Resistance(Rprime_wood,name='wood')
U_glass= Resistance(Rprime_glass, name='glass')

#####Computing total heat transfer coefficient(Utot) and total Resistance of wall(R_tot_wall) #####

Utot = 0.25*float(U_wood) + 0.75*float(U_glass)
R_tot_wall = round((1/Utot),4)
print('The total wall unit resistance is ' + str(R_tot_wall)+ ' °C/W.m^2')

####Computing rate of heat loss through the wall, Q#####

T_inside= 22
T_outside = -2
wall_perimeter = 50
wall_heigth = 2.5
glazing_fraction = float(20)/100
A_tot = wall_perimeter * wall_heigth
A_actual = A_tot*(1-glazing_fraction)
Q = round((Utot * A_actual * (T_inside - T_outside)),4)
print("The rate of heat loss through the wall is "+ str(Q)+ " W")
        
 
